version: '3.8'

services:
  library-management-mysql:
    image: mysql:5.7
    container_name: library-management-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=library2
      - MYSQL_ROOT_PASSWORD=Maverick.30
    volumes:
      - library-management-mysql-volume:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  library-management-mysql-volume: