spring:
  application:
    name: library-management

  datasource:
    url: jdbc:mysql://localhost:3306/library2
    username: root
    password: Maverick.30

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  thymeleaf:
    cache: false
    enabled: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    org:
      springframework:
        security: DEBUG
