spring:
  application:
    name: library-management

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/library2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  thymeleaf:
    cache: true
    enabled: true

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ADMIN

  messages:
    basename: messages

logging:
  level:
    org:
      springframework:
        security: WARN
